### ISSUE TITLE
MACS ONLY - Crash on pressing Play - needs more data and info

### ISSUE THREAD

**Issue by Amazonys** [Amazonys/Imperialism-Reinvigorated#100]
Pretty self explanatory.

Confirmed on my Macbook, as well as Hope's

**Comment by Pbhuh** [comment]
Possible thing to look into is:
Byzantium. Apperently there are crash to desktops on this nation, maybe thats whats behind it

**Comment by Amazonys** [comment]
Seems to be resolved and known issue now. Tag issues either with Oceania or # of tags.
