### ISSUE TITLE
Bugs in south eastern asia

### ISSUE THREAD

**Issue by Tavotev** [Amazonys/Imperialism-Reinvigorated#101]
-a lot of tech group icons are messed up
![kinija](https://user-images.githubusercontent.com/44952534/57566450-5f8fd200-73d5-11e9-9c78-73870ceccd5e.PNG)
![trade](https://user-images.githubusercontent.com/44952534/57566328-db891a80-73d3-11e9-9479-b1ee8e86d5bd.PNG)
-some trade nodes have their first letter a minor one, like "sunda" or "brunei"
-for some god forsaken reason i can change my government into a Roman Autocracy as majapahit
![eu4_135](https://user-images.githubusercontent.com/44952534/57566355-1e4af280-73d4-11e9-90b3-e05828850eda.png)
-i dont know if this is intended,but the flag for Favorlang looks like pixel vomit
![vomit](https://user-images.githubusercontent.com/44952534/57566626-e0e86400-73d7-11e9-9fc7-1e975c8ad2f5.PNG)
-the gov type Chief Council is not selected as the first gov reform,the same goes for Clan Council;
![eu4_137](https://user-images.githubusercontent.com/44952534/57566643-315fc180-73d8-11e9-8c6e-8b2871aff265.png)
-

**Comment by Amazonys** [comment]
Fixed tech group icons, localization for tradenodes. 
Favorlang is intentionally awful, but historical
Will get to the rest soon
