### ISSUE TITLE
Oceania Issues ~ Please add bugs spotted in Oceania in the comments

### ISSUE THREAD

**Issue by LeRoi6** [Amazonys/Imperialism-Reinvigorated#102]
-Areas need localization
-Units and Ships need localization
-Melanesia Charter Company needs localization
-Catamaran and Canoe sprite is a Western Soldier
-Selecting Pitkern Island #11545 causes a CTD
-Macuata has a Western gfx soldier

**Comment by Amazonys** [comment]
Areas localized,
? on charter
Fixed Pitkern
Macuata fixed

**Comment by Amazonys** [comment]
Fixed all of these save the boat gfx
