### ISSUE TITLE
Styria -> Austria missions

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#104]
When Styria integrates Austria they don't seem to get the Austrian missions

**Comment by Jupiter0-0** [comment]
Should be (semi)fixed with the reintroduction of formable austria

**Comment by Plutarc0** [comment]
> Should be (semi)fixed with the reintroduction of formable austria

Hi @Jupiter0-0 , what do you mean semi fixed?

**Comment by Jupiter0-0** [comment]
Sorry, semifixed means I didnt fix the actual bug. I removed the automatical tag change in this event and reintroduced the form austria decision. So STY will get austria missions now through the decision, but the decision itself needs a lot of polishing and localisation.
