### ISSUE TITLE
Permanent claims seem to not give a valid CB as BYZ

### ISSUE THREAD

**Issue by mgrinshpon** [Amazonys/Imperialism-Reinvigorated#107]
On the stable release, as BYZ, permanent claims from the following missions do not result in a valid conquest CB:
- byz_reconquer_west_anatolia
- byz_safeguard_balkan_border
- byz_expand_naval_dominance

Interestingly enough, the tooltip for "Declare War" in the diplomacy screen shows me having claims but when going to the declare war screen, there is no conquest CB. Guess the UI calculates these things differently?

**Comment by Jupiter0-0** [comment]
fixed
