### ISSUE TITLE
Lagging and crashing in Stable Version

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Imperialism-Reinvigorated#108]
I have noticed that the game is lagging a lot and there have been a couple of users complaining about crashes around 1450/60. We should focus on stabilising the current build and put a hold on deploying any new features. What do you guys think?

**Comment by Atlantispy** [comment]
I think we should halt development of all new features until we're bug free and better performance.

**Comment by Amazonys** [comment]
I believe that the crashing has been resolved, and the lag due to development mitigated greatly. Closing this issue for now.
