### ISSUE TITLE
Colonial Range from tech

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#11]
Please add +60 base colonial range to tech 3

**Comment by Hope915** [comment]
Correction! Tech 0, I've learned that it's intimately tied to coring distance...

**Comment by Amazonys** [comment]
I'm still confused at what you want done.

**Comment by Pbhuh** [comment]
Is this a bug or a balance request? Because im unsure as well.

**Comment by Amazonys** [comment]
Yeah I reverted the change, I'm just not sure what Hope is looking to change exactly

**Comment by Pbhuh** [comment]
closing it for now, seems fixed?

**Comment by Hope915** [comment]
For context, my request was "Please add +60 base colonial range to tech 0"

For context, the reverted change is an overcorrection, giving +160 at game start and allowing Portugal to discover Elmina instantly, for example.
