### ISSUE TITLE
Various Bugs - split out 

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Imperialism-Reinvigorated#110]
- [x] - The entire world has the alajamento province modifier, blocking all colonization

- [x] - the cb i got from missions (permanent claims) don't show up when I try to declare war on someone. In the diplomacy section, I see that I have CB on several countries, but when I click on the declare war button, I can only do a no cb war (or excommunicated, or insult, or whatever, but no cb from the claims i got from the mission)

- [x] -Similiar problem with alajamento, can't do anything except war with natives and get mission provinces until 1615

- [x] -Can't declare war on some countries, says IR_NO_CIVIL_WAR, but I'm not sure what that means. Could be normal gameplay, I don't know

- [ ] -Release Ireland decision doesn't seem to make it a viceroyalty as the decision text suggests, but actually just frees it as a republic.

Problem 1 

Mission por_ouro_da_guine : I already discovered Elmina but the discovery of Elmina requirement remain unchecked

Problem 2 

The following mission, por_sao_tome_principe rewards me once completed with permanent claim on all states, leading to a crash

Problem 3 

The modifier alojamento triggered in all uncolonized provinces

**Comment by Pbhuh** [comment]
Thanks, Problem 4 can be the cause of people not being able to declare on nations or gain claims.

**Comment by Pbhuh** [comment]
Thanks, Problem 4 can be the cause of people not being able to declare on nations or gain claims.
