### ISSUE TITLE
Wattasid Conspiracy event

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#12]
Reintroduce “Wattasid Conspiracy” event to shatter Morocco when mission “Control Tânger” is taken.

**Comment by Amazonys** [comment]
I'm just going to have it break up the fiefdoms of Morocco, that fine?

**Comment by Atlantispy** [comment]
Would it make sense to have them break off and declare a war to install a new ruler (someone of Wattasid dynasty)?

**Comment by Amazonys** [comment]
I think there is already a vanilla event. Let me search around for it
