### ISSUE TITLE
Ottomans need buffs

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#28]
Ottomans consistently lose to Hungary, needs buffing in some form

**Comment by Atlantispy** [comment]
From my test games I've always seen them have large armies, but they split it up to start sieging, and is then targeted by a death stack of Hungarians and their vassals.

Land maintenance cost reduction and a bit of manpower if Hungary specifically declares war on them?

They definitely get a lot stronger when they take Byzantium first so if we can force that DoW it'd help.

**Comment by Amazonys** [comment]
I am thinking about quickly reworking the Ottoman mission tree...

**Comment by Amazonys** [comment]
Still pretty underpowered. I'm closing this one but keeping the one about their missions open
