### ISSUE TITLE
Occitano-Romance culture group?

### ISSUE THREAD

**Issue by Amazonys** [Amazonys/Imperialism-Reinvigorated#49]
Axuba recently pitched an idea in which we move Catalan and Occitan to their own culture group. Not against the idea on principle, but my concerns are related to gameplay and whether this will have a substantial negative effect on the stability of France and Spain. Please post your thoughts!

**Comment by Pbhuh** [comment]
I am interested in adding this, but I want new mechanics in this regard as well. 

Currently the culture thing is not very flexible and it damages cultural proximity, say the germanic group vs french group. Ideally one would be able to make a Romance Group or at least Gallo-Romance ish group and split cultures into subgroups. 

The subgroup system would have to be implemented in two possible ways, either you unify them all and add in negative modifiers for specific culture groups, or you split all the current groups and add in positive modifiers to buff certain major groupings. Not sure what would be the wisest in that regard as both cause issues.

**Comment by Axuba** [comment]
Also need to say (since I think there's been a small misunderstanding) that the group should be:

- Catalan
- Occitan
- Gascon
- Provençal

Not only Catalan and Occitan; Gascon and Provençal are considered Occitan dialects.

**Comment by mgrinshpon** [comment]
Wikipedia has a concise summary of the dialects available here: https://en.wikipedia.org/wiki/Occitan_language#Dialects

**Comment by Amazonys** [comment]
done
