### ISSUE TITLE
Eventgrouping IR_hurricanes

### ISSUE THREAD

**Issue by Pbhuh** [Amazonys/Imperialism-Reinvigorated#51]
Im getting a lot of issues with IR_hurricanes, if someone else could have a look at it that be great. I think the problem is that the event IDs are not organized properly by a numeral system:

here a quick copy:
id = IR_hurricanes.3a
	title = "IR_hurricanes.t"
	desc = "IR_hurricanes.d"

im pretty sure it needs to be 
IR_hurricanes.3 
and IR_hurricanes.3.t
etc.

Please some help here.

**Comment by Amazonys** [comment]
Probably, I'll move it to a cut folder for now. I will revisit these events soon (ish)
