### ISSUE TITLE
Japan Issues

### ISSUE THREAD

**Issue by Amazonys** [Amazonys/Imperialism-Reinvigorated#52]
Japan formable missing
Not enough states
4-5 nonexistent nations still exist in game (Ikkaku for sure)
Ghost provinces in Asia

**Comment by Pbhuh** [comment]
Makes sense, leftover damage from china. I will see what I can do this fix this.

**Comment by Amazonys** [comment]
Awesome! I have added the Japan formable back in, no worries there

**Comment by Amazonys** [comment]
Donezos
