### ISSUE TITLE
France timeline

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#55]
In progress, mainly being done by Victoria

**Comment by Plutarc0** [comment]
@Atlantispy  are these the same as the mission trees? Is Victoria someone that we can assign to this card?

**Comment by Pbhuh** [comment]
these would be historical timeline events of france everyone from things such as conquest of regions, provinces, events etc.

**Comment by Pbhuh** [comment]
![afbeelding](https://user-images.githubusercontent.com/43622113/57256802-e6505200-7057-11e9-8178-e4fc40e82f47.png)
![afbeelding](https://user-images.githubusercontent.com/43622113/57256823-f9fbb880-7057-11e9-89c4-97aa0a7db5b7.png)
![afbeelding](https://user-images.githubusercontent.com/43622113/57256838-06801100-7058-11e9-917a-5550bcc5221b.png)
![afbeelding](https://user-images.githubusercontent.com/43622113/57256853-0f70e280-7058-11e9-97b8-bbf78c37dd46.png)
![afbeelding](https://user-images.githubusercontent.com/43622113/57256866-1992e100-7058-11e9-848f-24d75786ebaa.png)
![afbeelding](https://user-images.githubusercontent.com/43622113/57256881-257ea300-7058-11e9-871a-86d6d5789c15.png)
![afbeelding](https://user-images.githubusercontent.com/43622113/57256896-316a6500-7058-11e9-8934-837d2526af27.png)

**Comment by Pbhuh** [comment]
https://docs.google.com/document/d/1k9S2CYlXcPw-UNcIxx_DxQf_47GC8jOhXkr5myBYBLQ/edit

**Comment by johnnygaddem** [comment]
Hi, I would like to help. Anyone has what had been already done? 

I’m french and very interested in history. Furthermore your mod is great, I would happy to help.

**Comment by johnnygaddem** [comment]
Hi, any way to help?

**Comment by Plutarc0** [comment]
> Hi, any way to help?

Can you join us on Discord to discuss this?- https://discord.gg/5K6NK9  Pieter is currently looking at France's timeline so will be able to update you on what's been done to date.
