### ISSUE TITLE
Portugal Mission localisation

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#6]
In Progress

See: https://docs.google.com/document/d/1EjMqzcJxFKUZEWl6p-w7deYepVt0gfbbGireKRvm8jM/edit

**Comment by Amazonys** [comment]
Nice! I will put it in either tonight or tomorrow morning for the next build

**Comment by Atlantispy** [comment]
@Amazonys This all implemented and can be closed?
