### ISSUE TITLE
Formables reportedly not working

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#61]
Spain, Japan, Qing, Yuan

Lusitania decision doesn't show up apparently

**Comment by Pbhuh** [comment]
lusitania should show up under these conditions:
potential = {
			NOT = { has_country_flag = formed_lusitania_flag }
			NOT = { tag = IBE }
			NOT = { tag = SPA }
			NOT = { tag = CAS }
			NOT = { tag = ARA }
			NOT = { tag = LSA }
			NOT = { tag = ADU }
			NOT = { tag = GRA }
			NOT = { tag = KNI }
			capital_scope = { region = iberia_region }
			IBE = { exists = no }
			LSA = { exists = no }
			is_nomad = no
			NOT = { religion_group = muslim }			#Muslims go for Andalusia
			OR = {
				tag = POR
				tag = BGC
				tag = CIM
				tag = BJ1
				tag = VSU
				primary_culture = portugese
			}
		}

**Comment by Atlantispy** [comment]
Okay, @Amazonys mentioned that it was due to a missing bracket, however the other person had the Spanish decision, apparently just did nothing when it was clicked.

**Comment by Amazonys** [comment]
Should already be fixed.
