### ISSUE TITLE
List of nations without starting rulers

### ISSUE THREAD

**Issue by Pbhuh** [Amazonys/Imperialism-Reinvigorated#63]
Here is a list of nations without starting rulers reported by others on the discord and steam:

Im going to expand on this list with suggestions posted by others here.
I'll fix these later.

Württemberg minors
HRE minors

**Comment by Atlantispy** [comment]
Count of Artois was Philip the Good, so a PU with Burgundy

**Comment by Pbhuh** [comment]
All of Burgundy got pu'd now that the dip slot req. Is removed.
