### ISSUE TITLE
HRE religious peace

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#66]
HRE starts with religious peace, making league wars impossible as far as I can tell. - Steam user

**Comment by Amazonys** [comment]
Aware of this and am looking into it.

**Comment by Pbhuh** [comment]
Got a Workaround fix for this,
Im assuming there is an event or vanilla problem where it auto institutes this one line,
currently im have set up an event to set it up properly again.

**Comment by Plutarc0** [comment]
Is this still an issue?

**Comment by Amazonys** [comment]
I'm not sure. Needs reconfirmation. @Plutarc0
