### ISSUE TITLE
Rebel bug?

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#68]
-There's some weird stuff with rebels. I noticed a 30k stack of Danish pretender rebels seige down province in Brandenburg for a couple decades in the late 1400s. Very bad for Brandenburg as they couldn't defeat the army and it wasn't enforcing its demands on Denmark. Might be an issue with rebel types not set to relocate? - Steam User

**Comment by Amazonys** [comment]
I buffed rebels too hard. Am looking into solutions.

**Comment by Pbhuh** [comment]
solved for now
