### ISSUE TITLE
French Mission tree

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Imperialism-Reinvigorated#80]

**Comment by Pbhuh** [comment]
I am confused how does this work? Is this a way to write down to do stuff?

**Comment by Atlantispy** [comment]
> I am confused how does this work? Is this a way to write down to do stuff?

Yeah, can write down progress, stuff to do etc.

**Comment by Pbhuh** [comment]
Alright, currently the design is about finished. Needs some polish, functionality and after that playtesting.

I will post some images I posted to discord here as well. 

I'm about to include maybe milanese conquest missions, savoy royal marriage and Navarra related missions and Catalonia missions ending with a Spanish Portugese mission for napoleonic times.
