### ISSUE TITLE
Galicia and Extremadura show as dominions of Leon

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Imperialism-Reinvigorated#84]
Extremadura should already be incorporated into Leon by 1444. At the time of the union of Castile and Leon, only Galicia had representation in the Cortes, which might make a case for it showing as a separate reino, but not Extremadura.

**Comment by Atlantispy** [comment]
I agree, I never actually wanted Extremadura to be unincorporated.

**Comment by Amazonys** [comment]
I made the decision to represent Extremadura, despite being slightly historically inaccurate. My understanding was that while it did not hold representation in the Cortes, it's relative autonomy was quite large, given its geographic position and recent depopulation relative to other areas nearby. Furthermore, a number of notable conquistadors and explorers come from the Extremadura region, so I decided to represent it. It helps with balancing the War of Castilian Succession.

**Comment by Plutarc0** [comment]
@Amazonys May I suggest increasing autonomy or adding a modifier, like in Monaco instead? The region of Extremadura was never a kingdom like Leon or Badajoz, so it is really jarring to see it represented.

https://es.wikipedia.org/wiki/Provincia_de_Extremadura

**Comment by Plutarc0** [comment]
Long discussion on discord, but I think there is now a consensus to remove Extremadura.
