### ISSUE TITLE
Question of the Cortes Gerais as an estate

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Imperialism-Reinvigorated#85]
This should be rethought as the current system does not represent the purpose of the Cortes. These were simply gatherings of the estates, like a parliament. The current system is a disservice to a political institution that is regarded as the 'cradle of parliamentarism'. 

https://en.wikipedia.org/wiki/Cortes_of_Le%C3%B3n_of_1188 

The system in Portugal was similar to the castillian cortes, so we should consider implementing the following:

- Iberian Monarchy:
1. Reinos subjects to a Crown
2. Parliament enabled
3. Nobility Estate enabled
4. Increased influence of the Nobility estate
5. Some sort of buff against Heathens.

**Comment by Atlantispy** [comment]
I'd agree with it

**Comment by Amazonys** [comment]
Okay, I might be on board with this. Would like to hear opinions from @Hope915 though, as the Cortes is his baby to a degree
