### ISSUE TITLE
Beja present at game start.

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Imperialism-Reinvigorated#87]
Portuguese Civil War event should spawn Beja from cores with starting regiments to beef up duke’s side

**Comment by Atlantispy** [comment]
Still not sure we need this tag as anything but a releasable, wasn't created until 1453, just spawn Coimbra with more troops.

**Comment by Plutarc0** [comment]
> Still not sure we need this tag as anything but a releasable, wasn't created until 1453, just spawn Coimbra with more troops.

Minor correction, if we are taking this approach, then it should spawn Viseu with more troops (the duke of Viseu was the 1st duke of Beja)

**Comment by Amazonys** [comment]
Please advise. If Beja goes, what other minor Portuguese dukedoms should exist in 1444? @Plutarc0 @Atlantispy @Hope915

**Comment by Atlantispy** [comment]
Historically? None.

You could have whatever Henry the Navigator was duke of choose whether to take a side I guess, but they didn’t historically get involved in the civil war.

**Comment by Amazonys** [comment]
Algarve? Might be interesting. In that case, I will remove Beja, but leave cores

**Comment by Atlantispy** [comment]
Algarve absolutely not, was never a duchy, an autonomy of any kind

**Comment by Plutarc0** [comment]
@Amazonys @Atlantispy  At game start we should have Coimbra, Viseu and Braganca as dukedoms, same as now.

https://en.wikipedia.org/wiki/Duke_of_Coimbra (Infante Pedro - uncle of Afonso V, the regent in 1444)
https://en.wikipedia.org/wiki/Duke_of_Braganza (Afonso, bastard uncle)
https://en.wikipedia.org/wiki/Duke_of_Viseu (Henry the navigator)

Before the battle, Henry the navigator (duke of Viseu) as well as the count of Avranches (the 2 star general) tried to calm down the monarch, to no avail, and as such **did not participate in the hostilities, it seems**. 

During the conflict, the choices should be:

Braganca declares war on portugal and coimbra  (on this event, I would wager that Viseu would have joined on Afonso's side as they had intervened on behalf of the duke of coimbra).

Portugal declares war on Coimbra, with Braganca (Viseu would remain neutral).

However, I understand that for a vassal to not join they may have to be turned into another kind of subject, so I think it would be fine to just have viseu join whichever side Portugal is on.

This is the relevant battle:
https://pt.wikipedia.org/wiki/Batalha_de_Alfarrobeira

**Comment by Amazonys** [comment]
Fixed.
