### ISSUE TITLE
Question of the Cortes Event

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#9]
Implement event detailed in More-tugal document as reward for "Reorganise the Cortes" mission

https://docs.google.com/document/d/1t7YoX9t-tmi2uT2MHqlIjiMf1mDePF7xcjUwO5_VT8Q/edit

#6

**Comment by Pbhuh** [comment]
Wait where is this event in the document? im really lost looking at all the information.

**Comment by Atlantispy** [comment]
Can't @ hope as he's not in the organisation yet, but I'd ask him

**Comment by Hope915** [comment]
Event is under description "Duke of Braganca D. Fernando executed."

**Comment by Atlantispy** [comment]
@Hope915 @Pbhuh This implemented now?
