### ISSUE TITLE
Playing as Portugal: Kilwa somehow ceased being my vassal.

### ISSUE THREAD

**Issue by Plutarc0** [Amazonys/Imperialism-Reinvigorated#93]
Hey @Hope915 , any more info on how to replicate this? How did it happen?

**Comment by Amazonys** [comment]
Will fix this by simply reworking that whole Kilwa-Portugal interaction

**Comment by Amazonys** [comment]
Any ideas are welcome.

**Comment by Plutarc0** [comment]
@Amazonys I'll outsource some of this to the Africa channel on the discord because the interaction should have a few components:

-  ministerial coups in Kilwa (there were 2 between 1450 and 1470)
- Internal conflicts (rulers ruling for about a year and then being assasinated, deposed, etc)
- Pero da Covilha (disguised as an arab merchant) arrives in Sofala in 1489 (around the same time of the rounding of the cape of good hope) - Portugal finds out that there's gold in the area.
- Portugal harasses Mombasa, Kilwa and Zanzibar
- Portugal installs a sultan in Kilwa and they pay vassalage.

**Comment by Amazonys** [comment]
These sound great. I can implement some events for kilwa and portugal. The cape of good hope mission ought to trigger the Pero da Covilha event (which explores to Sofala)
