### ISSUE TITLE
Integration of National Ideas Expanded.

### ISSUE THREAD

**Issue by Atlantispy** [Amazonys/Imperialism-Reinvigorated#97]
https://steamcommunity.com/sharedfiles/filedetails/?id=1592328478&searchtext=ideas

Not near term, after SEA and Iberia polish.

**Comment by Amazonys** [comment]
YES YES YES. will get on this soon

**Comment by Plutarc0** [comment]
Maybe move this to the British Isles update?

**Comment by Amazonys** [comment]
Should be integrated now.
