### ISSUE TITLE
Castile Mission Tree: Christianize the Canaries 

### ISSUE THREAD

**Issue by Michael7123** [Amazonys/Imperialism-Reinvigorated#99]
This mission has no requirements to complete it, and gives no rewards upon completion, and has no localization for it's description.

**Comment by Amazonys** [comment]
Uh-oh, will get on this shortly

**Comment by Pbhuh** [comment]
Missions without requirements or completion rewards are an easy way to keep connectivity and not lock other missions later on.

While obviously a bug it is less important as it doesnt effect gameplay as hard.
